/**
 * Turns the design's he.js (a `window.GOTCHA_HE = {...}` script) into a module.
 *
 * Kept as JavaScript, verbatim: the dictionary has duplicate keys, which is
 * legal JS (the last wins, and that is what the design renders) but a
 * TypeScript error. Rewriting it to satisfy the compiler would be editing the
 * copy, so the file stays untyped instead.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DESIGN = path.join(ROOT, 'design');

let src = fs.readFileSync(path.join(DESIGN, 'he.js'), 'utf8');

const GLOBAL = 'window.GOTCHA_HE = {';
if (!src.includes(GLOBAL)) throw new Error('GOTCHA_HE assignment not found');
src = src.replace(GLOBAL, 'export const HE_DICT = {');

const out = path.join(ROOT, 'src/generated/he.js');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, '/* GENERATED by tools/build-he.mjs from design/he.js - do not edit. */\n' + src);

const keys = [...src.matchAll(/(?:^|[{,]\s*)(['"])((?:\\.|(?!\1).)*)\1\s*:/gs)].map((m) => m[2]);
const seen = new Set();
const dupes = keys.filter((k) => (seen.has(k) ? true : (seen.add(k), false)));

console.log('he.js:', keys.length, 'entries,', seen.size, 'distinct');
if (dupes.length) {
  console.log(`  ${dupes.length} duplicate key(s) - later values win, earlier ones are dead:`);
  [...new Set(dupes)].slice(0, 8).forEach((k) => console.log('   ', JSON.stringify(k.slice(0, 70))));
}
