/**
 * iCount authentication and configuration.
 *
 * API TOKEN ONLY. There is one authentication method and no fallback: a missing
 * token is a hard failure, never a downgrade to some other credential. Mixed
 * -mode auth is how a service ends up quietly sending a password because a
 * token lookup returned empty.
 *
 * There is deliberately no ICOUNT_AUTH_MODE knob. A setting whose only legal
 * value is the one thing the code does is not configuration, it is a chance to
 * misconfigure something that has no alternative.
 *
 * Transport is `Authorization: Bearer <token>` with a JSON body, verified
 * against iCount's own first-party integration, which builds every request as:
 *
 *     POST https://api.icount.co.il/api/v3.php/{action}
 *     Content-Type: application/json
 *     Authorization: Bearer {access_token}
 *
 * The token therefore never appears in a URL or a request body. Tokens are
 * created in the iCount UI under System -> Settings -> Automation -> API Tokens.
 *
 * Config (env, billing service only - never NEXT_PUBLIC):
 *   ICOUNT_MODE            "mock" (default) | "live"
 *   ICOUNT_API_TOKEN       the SID / API token
 *   ICOUNT_API_BASE_URL    default https://api.icount.co.il/api/v3.php
 *   ICOUNT_PAYMENT_PAGE_ID the "Credit card token" PayPage id - CONFIGURATION,
 *                          not a credential
 *   ICOUNT_WEBHOOK_SECRET  shared secret for callback verification
 *   ICOUNT_ALLOW_LIVE      explicit acknowledgement required to charge live
 */
import { redact } from "@chatcenter/shared";

const DEFAULT_API_BASE_URL = "https://api.icount.co.il/api/v3.php";

/**
 * Mock mode makes no network calls at all, so it needs no credentials and can
 * never charge anything. Resolved at CALL time so tests and runtime config
 * changes are honoured.
 */
export function isMock(): boolean {
  return String(process.env.ICOUNT_MODE || "mock").toLowerCase() !== "live";
}

export function icountApiBaseUrl(): string {
  return (process.env.ICOUNT_API_BASE_URL || DEFAULT_API_BASE_URL).replace(/\/+$/, "");
}

/**
 * The tokenization PayPage id.
 *
 * Configuration, not a secret: it identifies which hosted page to send a
 * customer to and grants no access on its own. It is still server-side only,
 * because the checkout URL is generated by the backend.
 */
export function icountPaymentPageId(): string | null {
  const id = (process.env.ICOUNT_PAYMENT_PAGE_ID || "").trim();
  return id || null;
}

/**
 * The API token, or a hard failure.
 *
 * Deliberately throws rather than returning empty: an unauthenticated call to
 * a payments API must never be attempted, and a caller that forgot to check
 * should crash here rather than send a request with no Authorization header.
 */
export function icountApiToken(): string {
  const token = (process.env.ICOUNT_API_TOKEN || "").trim();
  if (!token) {
    throw new Error(
      "[icount] ICOUNT_API_TOKEN is not configured - refusing to call the iCount API unauthenticated (there is no credential fallback)",
    );
  }
  return token;
}

/** Request headers for an authenticated call. Bearer transport, JSON body. */
export function authHeaders(): Record<string, string> {
  return {
    "Content-Type": "application/json",
    Authorization: `Bearer ${icountApiToken()}`,
  };
}

/**
 * Startup gate.
 *
 * Fails closed when the service is configured to talk to the real iCount API
 * without a token: better to refuse to boot than to run a billing service whose
 * every charge will fail at the worst possible moment.
 *
 * Mock mode is exempt because it performs no network calls and holds no
 * credentials by design - requiring a real token there would break every
 * development stack and CI run without protecting anything.
 */
export function assertIcountConfig(env: NodeJS.ProcessEnv = process.env): void {
  const mode = String(env.ICOUNT_MODE || "mock").toLowerCase();
  if (mode !== "live") return; // mock: no network, no credentials needed

  if (!(env.ICOUNT_API_TOKEN || "").trim()) {
    throw new Error(
      "[icount] ICOUNT_MODE=live requires ICOUNT_API_TOKEN - refusing to start a billing service that cannot authenticate",
    );
  }
}

/**
 * Mask secrets before anything reaches a log or an error message.
 *
 * The shared `redact()` covers Bearer headers and token-shaped fields. It
 * cannot know THIS service's token when it appears bare, so the configured
 * value is stripped literally as well.
 */
export function redactIcount(value: unknown): unknown {
  const safe = redact(value);
  const token = (process.env.ICOUNT_API_TOKEN || "").trim();
  if (!token || token.length < 8) return safe;
  try {
    const json = JSON.stringify(safe);
    if (!json || !json.includes(token)) return safe;
    return JSON.parse(json.split(token).join("[REDACTED]"));
  } catch {
    return safe;
  }
}

/**
 * Turn a provider/transport failure into a safe Error.
 *
 * An axios error carries `config.headers`, which holds the Authorization
 * header. Rethrowing it verbatim would put the API token into every log that
 * catches it, so the original is dropped entirely and only a redacted summary
 * survives.
 */
export function sanitizeIcountError(path: string, err: unknown): Error {
  const e = err as any;
  const status = e?.response?.status;
  const detail =
    e?.response?.data?.error_description ||
    e?.response?.data?.reason ||
    e?.message ||
    "request_failed";
  return new Error(
    `[icount] ${path} failed${status ? ` (HTTP ${status})` : ""}: ${String(redactIcount(detail))}`,
  );
}
