-- AlterEnum: Add EMAIL, GMAIL, OUTLOOK, SLACK to ChannelType
ALTER TYPE "ChannelType" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "ChannelType" ADD VALUE IF NOT EXISTS 'GMAIL';
ALTER TYPE "ChannelType" ADD VALUE IF NOT EXISTS 'OUTLOOK';
ALTER TYPE "ChannelType" ADD VALUE IF NOT EXISTS 'SLACK';
